### ISSUE TITLE
Update sponsors

### ISSUE THREAD

**Issue by ziggy6792** [waketools/alpaca-frontend#71]
For the sponsor logos, can you use this as shown in this layout

![WhatsApp Image 2021-04-20 at 11 21 58](https://user-images.githubusercontent.com/60313838/115332935-5ae01500-a1cb-11eb-8a1f-2d9ff5d3abb4.jpeg)

on top of the sponsor logos, you can put this

![489977a3-fc8d-4d0e-80ca-b584a8b2fc85](https://user-images.githubusercontent.com/60313838/115332967-6b908b00-a1cb-11eb-9206-b02947d7e964.jpg)
[Logos.zip](https://github.com/waketools/alpaca-frontend/files/6340858/Logos.zip)

**Comment by Alexander-Bychkov-1982** [comment]
Please use new Embily logo

**Comment by ziggy6792** [comment]
[Logos.zip](https://github.com/waketools/alpaca-frontend/files/6340849/Logos.zip)
